# Generated by Django 5.2.13 on 2026-04-16 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('base_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('institution', models.CharField(blank=True, max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='professors.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='professors.department')),
                ('professors', models.ManyToManyField(blank=True, related_name='courses', to='professors.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField(default=0)),
                ('avg_compound', models.FloatField(default=0.0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('theme_counts', models.JSONField(blank=True, default=dict)),
                ('recommendation_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='professors.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='professors.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professors.professor')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='professors.source')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.FloatField()),
                ('positive', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('negative', models.FloatField(default=0.0)),
                ('label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='professors.review')),
            ],
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.UniqueConstraint(fields=('name', 'institution'), name='uniq_professor_name_institution'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_course_code'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['professor', 'source'], name='professors__profess_1c95bd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['posted_at'], name='professors__posted__a047a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('source', 'source_url'), name='uniq_source_url'),
        ),
    ]
