# Generated by Django 5.2.12 on 2026-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("code", models.CharField(blank=True, max_length=16)),
            ],
        ),
    ]
