# Generated by Django 5.2.13 on 2026-09-17 16:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "professors",
            "0002_professor_external_ref_professor_source_avg_rating_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="professor",
            index=models.Index(
                django.db.models.functions.text.Lower("institution"),
                name="idx_prof_institution_lower",
            ),
        ),
    ]
