# Generated by Django 5.2.12 on 2026-03-21 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0002_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="professors.department",
            ),
        ),
    ]
