# Generated by Django 5.2.13 on 2026-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0003_professor_idx_prof_institution_lower"),
    ]

    operations = [
        migrations.AddField(
            model_name="professorstats",
            name="analysis_source",
            field=models.CharField(
                choices=[
                    ("seed", "Seed/demo data"),
                    ("live_rmp", "Live RateMyProfessors analysis"),
                ],
                default="live_rmp",
                max_length=16,
            ),
        ),
    ]
