# Generated by Django 5.2.12 on 2026-03-26 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0004_alter_professor_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("base_url", models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="professor",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="professor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professor",
            name="external_ref",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="professor",
            name="source_avg_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="source_num_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="professors.department",
                    ),
                ),
                (
                    "professors",
                    models.ManyToManyField(
                        blank=True, related_name="courses", to="professors.professor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfessorStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("avg_compound", models.FloatField(default=0.0)),
                ("positive_count", models.IntegerField(default=0)),
                ("neutral_count", models.IntegerField(default=0)),
                ("negative_count", models.IntegerField(default=0)),
                ("theme_counts", models.JSONField(blank=True, default=dict)),
                ("recommendation_score", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="professors.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("rating", models.FloatField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="professors.course",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="professors.professor",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="professors.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SentimentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compound", models.FloatField()),
                ("positive", models.FloatField(default=0.0)),
                ("neutral", models.FloatField(default=0.0)),
                ("negative", models.FloatField(default=0.0)),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=10,
                    ),
                ),
                ("themes", models.JSONField(blank=True, default=list)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment",
                        to="professors.review",
                    ),
                ),
            ],
        ),
    ]
