# Generated by Django 5.2.12 on 2026-03-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0005_source_professor_bio_professor_created_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="professor",
            constraint=models.UniqueConstraint(
                fields=("name", "institution"), name="unique_professor_name_institution"
            ),
        ),
    ]
