# Generated by Django 5.2.12 on 2026-03-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0006_professor_unique_professor_name_institution"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="professor",
            constraint=models.UniqueConstraint(
                fields=("external_ref",), name="unique_professor_external_ref"
            ),
        ),
    ]
