# Generated by Django 5.2.12 on 2026-03-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0006_professor_unique_professor_name_institution"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="professor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_ref", ""), _negated=True),
                fields=("external_ref",),
                name="unique_professor_external_ref",
            ),
        ),
    ]
