# Generated by Django 5.2.12 on 2026-03-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0007_professor_unique_professor_external_ref"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="professor",
            name="unique_professor_name_institution",
        ),
        migrations.AddConstraint(
            model_name="professor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_ref", "")),
                fields=("name", "institution"),
                name="unique_professor_name_institution",
            ),
        ),
    ]
