# Generated by Django 5.2.12 on 2026-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "professors",
            "0008_remove_professor_unique_professor_name_institution_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="professorstats",
            name="analysis_source",
            field=models.CharField(
                choices=[
                    ("seed", "Seed/demo data"),
                    ("live_rmp", "Live RateMyProfessors analysis"),
                ],
                default="live_rmp",
                max_length=16,
            ),
        ),
    ]
