# Generated by Django 5.2.12 on 2026-05-02 21:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0010_backfill_analysis_source"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="professor",
            index=models.Index(
                django.db.models.functions.text.Lower("institution"),
                name="idx_prof_institution_lower",
            ),
        ),
    ]
